const $=id=>document.getElementById(id);
let token=sessionStorage.getItem('inai-token')||'', selected=null, docs=[], timer=null;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,6500)}
async function api(path,options={}){const headers={Authorization:'Bearer '+token,...options.headers};if(options.body&&!(options.body instanceof FormData))headers['Content-Type']='application/json';const response=await fetch('/api'+path,{...options,headers});if(!response.ok){let msg;try{msg=(await response.json()).detail}catch{msg='Request failed ('+response.status+')'}throw Error(typeof msg==='string'?msg:'Please check your input')}return options.raw?response:response.json()}
async function busy(button,fn){button.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{button.disabled=false}}
async function unlock(){const status=await api('/status');sessionStorage.setItem('inai-token',token);$('gate').hidden=true;$('workspace').hidden=false;$('system').textContent='OCR: '+(status.ocrLanguages.join(', ')||'not installed')+' · AI: '+(status.modelConfigured?status.model+' (configured; availability checked on request)':'configure Ollama to enable');await refresh()}
$('unlock').onsubmit=e=>{e.preventDefault();token=$('token').value.trim();busy(e.submitter,unlock)};
$('lock').onclick=()=>{token='';sessionStorage.removeItem('inai-token');location.reload()};
async function refresh(){docs=await api('/documents?archived='+$('archived').checked);$('documents').innerHTML=docs.length?docs.map(d=>`<button class="doc-item ${d.id===selected?.id?'active':''}" data-doc="${d.id}">${escape(d.name)}<small>${escape(d.status)} · ${escape(d.language)}</small></button>`).join(''):'<p class="muted">No documents here yet.</p>';if(selected){const next=await api('/documents/'+selected.id);const changed=next.status!==selected.status;selected=next;if(changed)renderDocument()}}
$('archived').onchange=()=>{selected=null;$('document').hidden=true;$('empty').hidden=false;refresh().catch(e=>notice(e.message))};
$('upload').onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{const file=$('file').files[0];if(file.size>16*1024*1024)throw Error('Maximum file size is 16 MB');const body=new FormData();body.append('file',file);body.append('language',$('ocrLanguage').value);body.append('force',$('force').checked);const result=await api('/documents',{method:'POST',body});$('archived').checked=false;await choose(result.id);await refresh();$('file').value='';notice('Document queued for extraction')})};
async function choose(id){selected=await api('/documents/'+id);$('results').innerHTML='';renderDocument();await refresh()}
$('documents').onclick=e=>{const b=e.target.closest('[data-doc]');if(b)choose(b.dataset.doc).catch(e=>notice(e.message))};
function renderDocument(){$('empty').hidden=true;$('document').hidden=false;$('docName').textContent=selected.name;$('docMeta').textContent=selected.status+' · '+selected.pages.length+' pages · '+selected.language;$('archive').textContent=selected.archived?'Restore':'Archive';$('retry').hidden=selected.status!=='failed';$('page').innerHTML=selected.pages.map(p=>`<option value="${p.number}">${p.number}</option>`).join('');$('exportText').disabled=$('exportJson').disabled=selected.status!=='ready';renderPage()}
function renderPage(){const p=selected.pages.find(p=>p.number===Number($('page').value));$('pageText').textContent=p?p.text:selected.error||'Reading document. This can take a minute per scanned page…';$('pageMeta').textContent=p?('Page '+p.number+' · '+p.method+(p.confidence===null?'':' · OCR engine confidence '+p.confidence+'% (not accuracy)')):''}
$('page').onchange=renderPage;
function requireReady(){if(!selected||selected.status!=='ready')throw Error('Select a ready document first');return selected.id}
$('retry').onclick=e=>busy(e.target,async()=>{await api('/documents/'+selected.id+'/retry',{method:'POST'});await refresh()});
$('archive').onclick=e=>busy(e.target,async()=>{await api('/documents/'+selected.id,{method:'PATCH',body:JSON.stringify({archived:!selected.archived})});selected=null;$('document').hidden=true;$('empty').hidden=false;await refresh()});
async function download(format){const r=await api('/documents/'+requireReady()+'/export?format='+format,{raw:true});const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='document.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('exportText').onclick=e=>busy(e.target,()=>download('txt'));$('exportJson').onclick=e=>busy(e.target,()=>download('json'));
function results(rows){$('results').innerHTML=rows.length?rows.map(r=>`<div class="result">${escape(r.text)}<button class="quiet" data-page="${r.page}">View page ${r.page}</button></div>`).join(''):'<p class="muted">No matching evidence found. Try words from the document.</p>'}
$('results').onclick=e=>{const b=e.target.closest('[data-page]');if(b){$('page').value=b.dataset.page;renderPage();$('pageText').focus()}};
$('search').onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{const r=await api('/documents/'+requireReady()+'/search',{method:'POST',body:JSON.stringify({query:$('query').value})});results(r.results)})};
$('summary').onclick=e=>busy(e.target,async()=>{const r=await api('/documents/'+requireReady()+'/summary');results(r.sentences)});
$('ai').onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{const id=requireReady();$('results').textContent='Processing with your model…';try{const r=await api('/documents/'+id+'/ai',{method:'POST',body:JSON.stringify({action:$('action').value,language:$('outputLanguage').value,question:$('question').value,page:Number($('page').value)||null})});$('results').innerHTML=`<div class="result">${escape(r.text)}</div><p class="muted">${escape(r.notice)}</p>`+(r.pages||[]).map(p=>`<button class="quiet" data-page="${p}">Page ${p}</button>`).join('')}catch(e){$('results').textContent=e.message;throw e}})};
setInterval(()=>{if(token&&!$('workspace').hidden&&docs.some(d=>['queued','processing'].includes(d.status)))refresh().catch(e=>notice(e.message))},2500);
if(token)unlock().catch(()=>{sessionStorage.removeItem('inai-token');token='' });
